SET IDENTITY_INSERT dbo.Disciplines ON
INSERT INTO dbo.Disciplines ([Id], [Name], [SportId]) VALUES ('1','Track & Fields',1)
INSERT INTO dbo.Disciplines ([Id], [Name], [SportId]) VALUES ('2','Road Running',1)
INSERT INTO dbo.Disciplines ([Id], [Name], [SportId]) VALUES ('3','Race Walking',1)
INSERT INTO dbo.Disciplines ([Id], [Name], [SportId]) VALUES ('4','Cross Country Running',1)
INSERT INTO dbo.Disciplines ([Id], [Name], [SportId]) VALUES ('5','Mountain Running',1)
INSERT INTO dbo.Disciplines ([Id], [Name], [SportId]) VALUES ('6','Trail Running',1)
INSERT INTO dbo.Disciplines ([Id], [Name], [SportId]) VALUES ('7','Road Racing',2)
INSERT INTO dbo.Disciplines ([Id], [Name], [SportId]) VALUES ('8','Track Cycling',2)
INSERT INTO dbo.Disciplines ([Id], [Name], [SportId]) VALUES ('9','Cyclo Cross',2)
INSERT INTO dbo.Disciplines ([Id], [Name], [SportId]) VALUES ('10','Mountain Bike Racing',2)
INSERT INTO dbo.Disciplines ([Id], [Name], [SportId]) VALUES ('11','BMX racing',2)
INSERT INTO dbo.Disciplines ([Id], [Name], [SportId]) VALUES ('12','Swimming',3)
INSERT INTO dbo.Disciplines ([Id], [Name], [SportId]) VALUES ('13','Open Water Swimming',3)
INSERT INTO dbo.Disciplines ([Id], [Name], [SportId]) VALUES ('14','Sled Dog Racing',5)
INSERT INTO dbo.Disciplines ([Id], [Name], [SportId]) VALUES ('15','Alpine Skiing',4)
INSERT INTO dbo.Disciplines ([Id], [Name], [SportId]) VALUES ('16','Nordic Skiing',4)
INSERT INTO dbo.Disciplines ([Id], [Name], [SportId]) VALUES ('17','Freestyle Skiing',4)
INSERT INTO dbo.Disciplines ([Id], [Name], [SportId]) VALUES ('18','Snowboarding',4)
INSERT INTO dbo.Disciplines ([Id], [Name], [SportId]) VALUES ('19','Triathlon',6)
INSERT INTO dbo.Disciplines ([Id], [Name], [SportId]) VALUES ('20','Biathlon',7)
SET IDENTITY_INSERT dbo.Disciplines OFF